### ISSUE TITLE
Database Exception – yii\db\Exception

### ISSUE THREAD

**Issue by hdushku** [abhi1693/yii2-app-advanced-startup-kit#3]
When I run the setup I get these error:

``` php
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbtest.config' doesn't exist
The SQL being executed was: SELECT name, value FROM `config`
Error Info: Array
(
    [0] => 42S02
    [1] => 1146
    [2] => Table 'dbtest.config' doesn't exist
)
↵
Caused by: PDOException

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dbtest.config' doesn't exist
```

**Comment by abhi1693** [comment]
I have fixed all the errors related to the `installer`. Update your project by running `composer update` and re-run your application. Let me know if you need more help.

**Comment by epulgaron** [comment]
I've got my project updated but I've got this error
SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected
The SQL being executed was: SELECT name, value FROM `config`

Error Info: Array
(
    [0] => 3D000
    [1] => 1046
    [2] => No database selected
)

↵
Caused by: PDOException
SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

now when i try to put my db name in app/common/common/config/main.php i got this

Database Exception – yii\db\Exception
SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'sigac'
↵
Caused by: PDOException
SQLSTATE[HY000] [1044] Access denied for user ''@'localhost' to database 'sigac'

can you help me? I'm very interesting in your extension, thx

**Comment by abhi1693** [comment]
Remove the changes you made in the `app/common/config/main.php` and tell me what happens when you navigate to `localhost\your-app\backend`?

**Comment by abhi1693** [comment]
Remove the changes you made in the `app/common/config/main.php` and tell me what happens when you navigate to `localhost\your-app\backend`?

**Comment by abhi1693** [comment]
Closing this issue due to lack of feedback.
